{{- if .Values.externalSecret.database.cassandra.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api-server.fullname" . }}-cassandra-db-secret
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key: {{ .Values.externalSecret.database.cassandra.secretAlias }}
    name: cassandraSecret
  template:
    data:
      CASSANDRA_CONTACT_POINTS: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).contactPoints.join(",")).toString("base64") %>
      CASSANDRA_PORT: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).port).toString("base64") %>
      CASSANDRA_KEYSAPCE: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).keyspace).toString("base64") %>
      CASSANDRA_USERNAME: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).username).toString("base64") %>
      CASSANDRA_PASSWORD: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).password).toString("base64") %>
      CASSANDRA_DATACENTER: |
        <%= Buffer.from(JSON.parse(data.cassandraSecret).datacenter).toString("base64") %>
{{- end -}}

