{{- if .Values.externalSecret.database.mongo.enabled -}}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "api-server.fullname" . }}-mongo-db-secret
  labels:
    {{- include "api-server.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key: {{ .Values.externalSecret.database.mongo.secretAlias }}
    name: mongoSecret
  template:
    data:
      MONGO_URI: |
        <% let s = JSON.parse(data.mongoSecret) %><%= Buffer.from(`${s.protocol || "mongodb+srv"}://${s.username}:${s.password}@${s.host}/${s.extraParams || "?ssl=false" }`).toString("base64") %>
      MONGO_DATABASE: |
        <%= Buffer.from(JSON.parse(data.mongoSecret).dbname).toString("base64") %>
{{- end -}}

